---
- name: Deploy and run Flask application
  hosts: "{{ reqhosts }}"
  become: yes
  vars:
    pkg:
      - "python3"
      - "python3-pip"
    version_check:
      - "pip3 --version"
      - "python3 --version"
  tasks:
    - name: Ensure Python and pip are installed on Debian
      apt:
        name: "{{ pkg }}"
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'
    - name: Check pip version and python3 version
      shell: "{{ item }}"
      register: version_debian_output
      with_items: "{{ version_check }}"
    - debug:
        msg: "{{ item.stdout_lines }}"
      with_items: "{{ version_deb_output.results }}"

    - name: Ensure Python and pip are installed on Redhat
      yum:
        name: "{{ pkg }}"
        state: present
        update_cache: yes
      when: ansible_os_family == 'RedHat'
    - name: Check pip version and python3 version
      shell: "{{ item }}"
      register: version_redhat_output
      with_items: "{{ version_check }}"
    - debug:
        msg: "{{ item.stdout_lines }}"
      with_items: "{{ version_redhat_output.results }}"

    